version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: monthly
    commit-message:
      prefix: deps
      prefix-development: build(gomod)
    groups:
      aws:
        patterns:
          - github.com/aws/*
      hashicorp:
        patterns:
          - github.com/hashicorp/*
