version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: monthly
    commit-message:
      prefix: deps
    groups:
      hashicorp:
        patterns:
          - github.com/hashicorp/*
      dev:
        patterns:
          - github.com/stretchr/testify
      app:
        patterns:
          - "*"
