version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - err113
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocyclo
    - gosec
    - gosmopolitan
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nonamedreturns
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - spancheck
    - testifylint
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - rowserrcheck
    - sqlclosecheck
  settings:
    forbidigo:
      forbid:
        - pattern: ^(fmt\\.Print(|f|ln)|print|println)$
        - pattern: ^spew\.(ConfigState\.)?Dump$
      analyze-types: true
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/articulate/docker-bootstrap
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
