linters:
  presets:
    - bugs
    - error
    - performance
  enable:
    - gofmt
    - gofumpt
    - revive
    - gocyclo
    - misspell
    - whitespace
    - goimports
    - gosec
    - testpackage
    - lll
  disable:
    - scopelint
    - rowserrcheck
    - sqlclosecheck
    - maligned

linters-settings:
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/articulate/docker-consul-template-bootstrap
