linters:
  presets:
    - bugs
    - error
    - performance
  enable:
    - gofmt
    - gofumpt
    - revive
    - gocyclo
    - misspell
    - whitespace
    - goimports
    - gofmt
    - gosec
    - lll
    - unused
    - nonamedreturns
    - tenv
    - funlen
    - nestif
    - forbidigo
  disable:
    - scopelint
    - rowserrcheck
    - sqlclosecheck
    - maligned

linters-settings:
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/articulate/docker-consul-template-bootstrap
  forbidigo:
    analyze-types: true
    forbid:
      - ^(fmt\\.Print(|f|ln)|print|println)$
      - ^spew\.(ConfigState\.)?Dump$
