# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: docker-bootstrap
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - binary
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true # Use changelog from release-please
release:
  prerelease: auto
  use_existing_draft: true
git:
  prerelease_suffix: "-"
