version: '2.1'
services:
  app:
    build: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "vault-token"
      CONSUL_ADDR: "consul:8500"
    depends_on:
      - consul
      - vault

  consul:
    image: consul:latest
    command: "agent -dev -log-level info -client 0.0.0.0"

  vault:
    image: vault:latest
    command: server -dev-kv-v1 -dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-token"
    cap_add:
      - IPC_LOCK
