FROM lambci/lambda:build-nodejs12.x

ENV SERVICE_ROOT /service
ENV SERVICE_USER service

ADD https://raw.githubusercontent.com/articulate/docker-consul-template-bootstrap/<%= @git_commit %>/install.sh /tmp/consul_template_install.sh
RUN bash -e /tmp/consul_template_install.sh <%= @git_commit %> && rm /tmp/consul_template_install.sh

RUN groupadd $SERVICE_USER && useradd --create-home --home $SERVICE_ROOT --gid $SERVICE_USER --shell /bin/bash $SERVICE_USER
WORKDIR $SERVICE_ROOT

ENTRYPOINT ["/entrypoint.sh"]

CMD "/bin/sh"
