#!/bin/sh
# Load Docker secrets as environment variables
#
# Usage:
#   . /opt/secrets - Load environment variables into shell
#   /opt/secrets [command] - Run a command with environment variables

for secret in /run/secrets/*; do
    export "$(basename "$secret")=$(cat "$secret")"
done

exec "$@"
