#!/bin/sh
# Load Docker secrets as environment variables
#
# Usage:
#   . $0 - Load environment variables into shell
#   $0 [command] - Run a command with environment variables

if [ -d /run/secrets ]; then
    for secret in /run/secrets/*; do
        export "$(basename "$secret")=$(cat "$secret")"
    done
fi

exec "$@"
